media:
  input: src/images
  output: /images
  label: Images
content:
  - name: about
    label: About
    path: src/about.md
    type: file
    fields:
      - name: title
        label: Page title
        type: string
      - name: image
        label: Image
        type: image
      - name: body
        label: Body
        type: rich-text
  - name: contact
    label: Contact
    path: src/contact.md
    type: file
    fields:
      - name: title
        label: Page title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: recipes
    label: Recipes
    type: collection
    path: 'src/recipes'
    subfolders: true
    filename: "{primary}-{year}-{month}.md"
    view:
      fields: [ title, image, featured, tags ]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: image
        label: Image
        type: image
        required: true
      - name: tags
        label: Category
        type: select
        required: true
        options:
          multiple: true
          values:
            - vegan
            - vegetarian
  - name: site
    label: Site settings
    path: src/_data/website.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)